// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrBpGKUizhiILIiBL_FjZFiNl8P79HWE',
    appId: '1:347677877809:web:1ccf8ab492f6ee33c11710',
    messagingSenderId: '347677877809',
    projectId: 'dih-healthapp',
    authDomain: 'dih-healthapp.firebaseapp.com',
    storageBucket: 'dih-healthapp.firebasestorage.app',
    measurementId: 'G-1P4GB523SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfv7JiXHC4OuoIUGMoCRVlBqImYSHY-LY',
    appId: '1:347677877809:android:c1745875d4d8bc24c11710',
    messagingSenderId: '347677877809',
    projectId: 'dih-healthapp',
    storageBucket: 'dih-healthapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW81ZHNPeu2w8qLYVm36Qz7rfSzqyeFXM',
    appId: '1:347677877809:ios:5a158c1a8325da39c11710',
    messagingSenderId: '347677877809',
    projectId: 'dih-healthapp',
    storageBucket: 'dih-healthapp.firebasestorage.app',
    iosBundleId: 'com.example.dih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW81ZHNPeu2w8qLYVm36Qz7rfSzqyeFXM',
    appId: '1:347677877809:ios:5a158c1a8325da39c11710',
    messagingSenderId: '347677877809',
    projectId: 'dih-healthapp',
    storageBucket: 'dih-healthapp.firebasestorage.app',
    iosBundleId: 'com.example.dih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrBpGKUizhiILIiBL_FjZFiNl8P79HWE',
    appId: '1:347677877809:web:a7995155da36f170c11710',
    messagingSenderId: '347677877809',
    projectId: 'dih-healthapp',
    authDomain: 'dih-healthapp.firebaseapp.com',
    storageBucket: 'dih-healthapp.firebasestorage.app',
    measurementId: 'G-5YPN5WF1CY',
  );

}